package constants

const (
	DEFAULT_SELECT_LIMIT    = "100"
	PAGE_SIZE_DEFAULT_VALUE = "10"

	URL_EVENT_PREFIX   = "events"
	URL_BILLING_PREFIX = "billing"
	URL_STORAGE_PREFIX = "storage"

	HTTP_STATUS_SUCCESS = "success"
	HTTP_STATUS_FAIL    = "fail"
	HTTP_STATUS_ERROR   = "error"

	HTTP_CODE_200_OK                    = "200" //http.StatusOk
	HTTP_CODE_400_BAD_REQUEST           = "400" //http.StatusBadRequest
	HTTP_CODE_401_UNAUTHORIZED          = "401" //http.StatusUnauthorized
	HTTP_CODE_500_INTERNAL_SERVER_ERROR = "500" //http.StatusInternalServerError
	HTTP_REQUEST_HEADER_AUTHRORIZATION  = "Authorization"

	NETWORK_NAME_POLYGON = "polygon"
	COIN_NAME_USDC       = "USDC"

	TRANSACTION_STATUS_SUCCESS = "success"
	TRANSACTION_STATUS_FAIL    = "fail"

	URL_HOST_GET_COMMON      = "/common"
	URL_HOST_GET_HOST_INFO   = "/host/info"
	URL_SYSTEM_CONFIG_PARAMS = "/system/params"

	SOURCE_ID_OF_PAYMENT = 4

	LOCK_PAYMENT_STATUS_WAITING             = "Pending" //wait for lock payment
	LOCK_PAYMENT_STATUS_PROCESSING          = "Processing"
	LOCK_PAYMENT_STATUS_DEAL_SENT_FAILED    = "DealSentFailed"
	LOCK_PAYMENT_STATUS_UNLOCK_REFUNDED     = "UnlockRefundSucceeded"
	LOCK_PAYMENT_STATUS_UNLOCK_REFUNDFAILED = "UnlockRefundFailed"

	DEAL_STATUS_ACTIVE = "StorageDealActive"
	DEAL_STATUS_ERROR  = "StorageDealError"

	IPFS_URL_PREFIX_BEFORE_HASH = "/ipfs/"
	IPFS_File_PINNED_STATUS     = "Pinned"

	LOTUS_TASK_TYPE_VERIFIED = "verified"
	LOTUS_TASK_TYPE_REGULAR  = "regular"

	LOTUS_PRICE_MULTIPLE_1E18 = 1e18 // 10^18
	FILE_BLOCK_NUMBER_MAX     = 999999999999999
	TIME_HALF_AN_HOUR         = 30 * 60 * 1000

	SOURCE_FILE_STATUS_CREATED      = "Created"
	SOURCE_FILE_STATUS_TASK_CREATED = "TaskCreated"

	DEAL_FILE_STATUS_CREATED   = "Created"
	DEAL_FILE_STATUS_DEAL_SENT = "DealSent"
	DEAL_FILE_STATUS_CANCELLED = "Cancelled"
	DEAL_FILE_STATUS_FAILED    = "Failed"

	OFFLINE_DEAL_UNLOCK_STATUS_NOT_UNLOCKED  = "NotUnlocked"
	OFFLINE_DEAL_UNLOCK_STATUS_UNLOCKED      = "Unlocked"
	OFFLINE_DEAL_UNLOCK_STATUS_UNLOCK_FAILED = "UnlockFailed"

	DURATION_DAYS_DEFAULT = 525

	SOURCE_FILE_TYPE_NORMAL = 0

	SOURCE_FILE_UPLOAD_HISTORY_STATUS_CREATED = "Created"
	SOURCE_FILE_UPLOAD_HISTORY_STATUS_DELETED = "Deleted"
)
