'use strict'
module.exports = {
  NODE_ENV: '"production"',
  BASE_API: '"https://api.filswan.com/"',
  // BASE_URL: '"https://www.multichain.storage"',
  BASE_URL: '"https://swanipfs.com"',
  BASE_PAYMENT_GATEWAY_API: '"https://api.swanipfs.com/"',
  BASE_PAYMENT_GATEWAY_BSC_API: '"https://calibration-mcs-bsc.filswan.com/"',
  BASE_PAYMENT_GATEWAY_POLYGON_API: '"https://api.swanipfs.com/"',
  BASE_MAINNET_ADDRESS: '"https://filscan.io/tipset/dsn-detail"',
  BASE_CALIBRATION_ADDRESS: '"https://calibration.filscan.io/tipset/dsn-detail"',
  BASE_MUMBAI_ADDRESS: '"https://mumbai.polygonscan.com/"',
  BASE_BSC_ADDRESS: '"https://testnet.bscscan.com/"',
  BASE_POLYGON_ADDRESS: '"https://polygonscan.com/"',
  BASE_ECO_API: '"https://ecosystem-api.swanipfs.com/"',
  BASE_METASPACE: '"https://meta-api.multichain.storage/"',
  BASE_POLYGON_RPC: '"https://polygon-rpc.com"',
  BASE_ETHEREUM_RPC: '"https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"',
  BASE_ENV: 'true',
  MEDIUM_LINK: '"https://medium.com/@swanchain/"',
  DISCORD_LINK: '"https://discord.gg/Jd2BFSVCKw"',
  TWITTER_LINK: '"https://twitter.com/swan_chain"',
  GITHUB_LINK: '"https://github.com/filswan"',
  TELEGRAM_LINK: '"https://t.me/swan_chain/1"',
  BASE_EMAIL: "'contact@swanchain.io'"
}
