'use strict'
module.exports = {
  NODE_ENV: '"test"',
  BASE_API: '"http://192.168.88.216:5002/"',
  BASE_URL: '"http://192.168.88.216:8080/mcs"',
  BASE_PAYMENT_GATEWAY_API: '"http://192.168.88.41:8889/"',
  BASE_PAYMENT_GATEWAY_BSC_API: '"http://192.168.88.41:8892/"',
  BASE_PAYMENT_GATEWAY_POLYGON_API: '"https://api.multichain.storage/"',
  BASE_MAINNET_ADDRESS: '"https://filscan.io/tipset/dsn-detail"',
  BASE_CALIBRATION_ADDRESS: '"https://calibration.filscan.io/tipset/dsn-detail"',
  BASE_MUMBAI_ADDRESS: '"https://mumbai.polygonscan.com/"',
  BASE_BSC_ADDRESS: '"https://testnet.bscscan.com/"',
  BASE_POLYGON_ADDRESS: '"https://polygonscan.com/"',
  BASE_ECO_API: '"http://192.168.88.216:5005/"',
  BASE_METASPACE: '"http://192.168.88.41:5212/"',
  BASE_POLYGON_RPC: '"https://polygon-rpc.com"',
  BASE_ETHEREUM_RPC: '"https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"',
  BASE_ENV: 'false',
  MEDIUM_LINK: '"https://medium.com/@swanchain/"',
  DISCORD_LINK: '"https://discord.gg/7TTjw7cr"',
  TWITTER_LINK: '"https://twitter.com/swan_chain"',
  GITHUB_LINK: '"https://github.com/filswan"',
  TELEGRAM_LINK: '"https://t.me/swan_chain/1"',
  BASE_EMAIL: "'contact@swanchain.io'"
}
