# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run lint
    - run: npm ci
    - run: npm run build:test_u
    - run: npm test

  

#   eslint:
#       name: Run eslint scanning
#       runs-on: ubuntu-latest
#       permissions:
#         contents: read
#         security-events: write
#       steps:
#         - name: Checkout code
#           uses: actions/checkout@v3

#         - name: Install ESLint
#           run: |
#             npm install eslint@8.10.0
#             npm install @microsoft/eslint-formatter-sarif@2.1.7
#         - name: Run ESLint
#           run: npx eslint ./src
#             --ext .ts
#   build:
#     runs-on: ubuntu-20.04.2 LTS
#     strategy:
#       matrix:
#         node-version: [14.x, 16.x, 18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build:test_u
#     - run: npm test

  
